##########################
##### Drop2Inventory #####
##########################

##########################
#####  Permissions   #####
##########################

# drop2inventory.use
#   Allows to use the /drop2inv command and use automatic drop collection
#
# drop2inventory.others
#   Allows to toggle Drop2Inventory for other players
#
# drop2inventory.autocondense
#   Allows to use the auto-condense feature to turn ingots into blocks (see condense.txt)
#
# drop2inventory.tool.<tool>
#   Allows to use Drop2Inventory for the specified tool when "permissions-per-tool" is enabled
#   Available tools: pickaxe, axe, hoe, sword, shovel, hand
#
# drop2inventory.reload
#   Allows to reload the config file
#
# drop2inventory.debug
#   Allows to toggle debug mode

##########################
#####    Commands    #####
##########################

# You can also use "/drop2inventory" instead of "/drop2inv"

# /drop2inv
#   Permission: drop2inventory.use
#   Toggle automatic drop collection for the current Player
#
# /drop2inv <player>
#   Permission: drop2inventory.others
#   Toggle automatic drop collection for <player>
#
# /drop2inv reload
#   Permission: drop2inventory.reload
#   Reloads the config file
#
# /drop2inv debug
#   Permission: drop2inventory.debug
#   Toggle debug mode



# When set to true, Drop2Inventory is always enabled and cannot be disabled by players
# I suggest you set it to true if you use Drop2Inventory to reduce server lag
always-enabled: false

# Whether automatic drop collection is enabled by default for new players
# If set to false, players will have to enter /drop2inv once to enable automatic drop collection
enabled-by-default: false

# when set to true, block drops will be automatically collected if the plugin is enabled
collect-block-drops: true

# when set to true, block experience orbs will be automatically collected if the plugin is enabled
collect-block-exp: true

# when set to true, mob/entity drops will be automatically collected if the plugin is enabled
collect-mob-drops: true

# when set to true, mob/entity experience orbs will be automatically collected if the plugin is enabled
collect-mob-exp: true

# WILL BE OBSOLUTE IN 2.0.0+ because it will be toggleable per player with a permission
# when set to true, items will automatically converted to blocks when mining them
# if the player has the permission "drop2inventory.autocondense"
# e.g. 9 diamonds -> 1 diamond_block etc
auto-condense: false

# shows an actionbar message to a player once their inventory is full
warn-when-inventory-is-full: true

# when set to true, players with automatic drop collection DISABLED will be
# shown a message on how to enable Drop2Inventory
# when they break a block for the first time.
# consider setting this to true when you set enabled-by-default to false.
# see also -> message-when-breaking-block
show-message-when-breaking-block: true

# when set to true, players with automatic drop collection ENABLED will be
# shown a message on how to disable Drop2Inventory
# when they break a block for the first time.
# consider setting this to true when you set enabled-by-default to true.
# see also -> message-when-breaking-block2
show-message-when-breaking-block-and-collection-is-enabled: false

# when set to true, the messages are shown again when a player
# logs out and back in and then breaks a block again.
show-message-again-after-logout: true

# when enabled, players need the permissions "drop2inventory.tool.pickaxe"
# to auto pickup blocks farmed with a pickaxe, "drop2inventory.tool.hoe" for
# blocks farmed with a hoe, etc.
permissions-per-tool: false

# when enabled, Drop2Inventory will only put stuff into the hotbar when
# the regular inventory is full.
# when disabled, Items will be put into the hotbar if possible (default
# and vanilla behaviour)
# Consider enabling this when your players want to level their mcMMO
# "unarmed" skill
avoid-hotbar: false

# Whether to play a sound when picking up items
sound-enabled: true
sound-effect: ENTITY_ITEM_PICKUP
sound-volume: 1.0
sound-pitch: 1.0
sound-global: true

#################################
#####     Event priority    #####
#################################

# WILL BE OBSOLUTE IN 2.0.0+
# Normally, Drop2Inventory should run on the highest possible priority.
# However, there are some plugins known to clear the BlockDropItemEvent's
# drops list, for example EcoEnchants. This is bad as Drop2Inventory can
# then detect some drops only using the "Legacy drop detection" (see below).
# Please do not change this value unless you really know what it does or
# if I told you to do so.
# Available values are LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR
block-drop-item-event-priority: HIGH

#################################
##### Legacy drop detection #####
#################################

# WILL BE OBSOLUTE IN 2.0.0+
# when enabled, Drop2Inventory tries to detect items that other plugins drop
# using the World#dropItem methods.
# This allows Drop2Inventory to detect block drops that other plugins create
# in ominous ways.
# This will also detect drops by dispensers, cactus farms etc. but you
# can adjust that using the options below.
# I suggest you leave all settings in this section untouched, unless your
# server has huge automatic farms in which case you can either disable
# this completely, or adjust the hopper settings below.
detect-legacy-drops: true
detect-legacy-drops-range: 6

# WILL BE OBSOLUTE IN 2.0.0+
# When using "detect-legacy-drops", ignore items spawning on hoppers
# The vertical range checks up to X blocks below the item for hoppers
# The horizontal range additionaly checks to the sides.
# Example: You set vertical range to 10 and horizontal to 0. That means
# the hopper will be detected if it is up to 10 blocks below the item
# and has the same x and z coordinate.
# If you set the horizontal range to 5, the hopper can also be up to 5
# block away on the x and z axis from the item, while still being
# detected.
ignore-items-on-hoppers: true
ignore-items-on-hoppers-vertical-range: 20
ignore-items-on-hoppers-horizontal-range: 3

# WILL BE OBSOLUTE IN 2.0.0+
# When set to true, items from dispensers and droppers will not automatically
# be collected by nearby players.
# When set to false, items from dispensers and droppers will automatically
# be collected by the closest player within "detect-legacy-drops-range" radius.
ignore-items-from-dispensers: true

# When set to true, Drop2Inventory will not automatically collect drops from
# mobs killed by lava or magma
ignore-drops-from-mobs-killed-by-lava: false
ignore-drops-from-mobs-killed-by-magma: false

# WILL BE OBSOLUTE IN 2.0.0+
# Other plugins can cancel the EntityPickupItemEvent, e.g. to make badly coded
# holograms (the other plugins should rather/additionally raise the Item#setPickupDelay)
# When the following setting is set to true, Drop2Inventory will call a fake
# EntityPickupItemEvent and do nothing if that gets cancelled.
call-entity-pickup-item-event: true

#########################
#### disabled worlds ####
#########################

# You can disable automatic drop collection for certain worlds.
# Each worlds's name has to be on a separate line, starting
# with a hyphen and followed by a space

# Example:
#
# disabled-worlds:
# - world
# - world_nether

disabled-worlds:

#################################
#### disabled/enabled blocks ####
#################################

# You can disable automatic drop collection for certain blocks.
# This can be helpful if you use plugins that change certain block drops
# because Drop2Inventory only detects "vanilla" drops.
# Each block's material name has to be on a separate line, starting
# with a hyphen and followed by a space

# Example:
#
# disabled-blocks:
# - spawner
# - grass_block

# If you wish to use a whitelist instead of a blacklist,
# change the "disabled-blocks:" to "enabled-blocks:"

disabled-blocks:

#################################
#### disabled/enabled mobs  ####
#################################

# You can disable automatic drop collection for certain mob types.
# This can be helpful if you use plugins that change certain mob drops
# because Drop2Inventory only detects "vanilla" drops.
# Each mob's name has to be on a separate line, starting
# with a hyphen and followed by a space

# Example:
#
# disabled-mobs:
# - bat
# - cave_spider

# If you wish to use a whitelist instead of a blacklist,
# change the "disabled-mobs:" to "enabled-mobs:"

disabled-mobs:

##########################
##### Update Checker #####
##########################

# Checks for updates (asynchronously).
# When enabled, a message is printed in the console if a new
# version has been found, and OPs will be notified when they join the server
# When set to true, check for updates on startup and every X hours (see "check-interval" below)
# When set to on-startup, only check on server startup
# When set to false, don't check for updates
check-for-updates: true

# When you set "check-for-updates" to true, you can define the amount
# of hours inbetween each update check.
check-interval: 4

#########################
##### localization ######
#########################

# Available color codes:
# &0 Black        &6 Gold       &c Red
# &1 Dark Blue    &7 Gray       &d Light Purple
# &2 Dark Green   &8 Dark Gray  &e Yellow
# &3 Dark Aqua    &9 Blue       &f White
# &4 Dark Red     &a Green
# &5 Dark Purple  &b Aqua

# Available formatting codes:
# &k Obfuscated   &m Strikethrough
# &l Bold         &o Italic
# &n Underline    &r Reset

# You can set messages to an empty String ("") to disable them.

##### English
message-disabled: "&7Automatic drop collection has been &cdisabled&7."
message-enabled: "&7Automatic drop collection has been &aenabled&7."
message-when-breaking-block: "&7Hint: Type &6/drop2inventory&7 or &6/drop2inv&7 to enable automatic drop collection."
message-when-breaking-block2: "&7Hint: Type &6/drop2inventory&7 or &6/drop2inv&7 to disable automatic drop collection."
message-inventory-full: "&cYour inventory is full."

##### Chinese Simplified
#message-disabled: "&7自动掉落物收集已 &c关闭&7."
#message-enabled: "&7自动掉落物收集已 &a开启&7."
#message-when-breaking-block: "&7提示: 输入 &6/drop2inventory&7 或 &6/drop2inv&7 以启用自动掉落物收集."
#message-when-breaking-block2: "&7提示: 输入 &6/drop2inventory&7 或 &6/drop2inv&7 以关闭自动掉落物收集."
#message-inventory-full: "&cYour inventory is full."

##### German
#message-disabled: "&7Automatisches Einsammeln &cdeaktiviert&7."
#message-enabled: "&7Automatisches Einsammeln &aaktiviert&7."
#message-when-breaking-block: "&7Hinweis: Benutze &6/drop2inventory&7 oder &6/drop2inv&7 um das automatische Einsammeln zu aktivieren."
#message-when-breaking-block2: "&7Hinweis: Benutze &6/drop2inventory&7 oder &6/drop2inv&7 um das automatische Einsammeln zu deaktivieren."
#message-inventory-full: "&cDein Inventar ist voll."

##### Korean
#message-disabled: "&7아이템 자동 줍기 기능이 &c비활성화 &7되었습니다."
#message-enabled: " &7아이템 자동 줍기 기능이 &a활성화 &7되었습니다."
#message-when-breaking-block: "&e/drop2inventory &7 또는 &6/drop2inv&7 명령어를 사용하여 아이템 자동 수집를 활성화 하세요."
#message-when-breaking-block2: "&e/drop2inventory &7 또는 &6/drop2inv&7 명령어를 사용하여 아이템 자동 수집를 비활성화 하세요."
#message-inventory-full: "&c현재 인벤토리가 가득 찼습니다."

##### Russian
#message-disabled: "&7Автоматический сбор дропа &cотключен&7."
#message-enabled: "&7Автоматический сбор дропа &aвключен&7."
#message-when-breaking-block: "&7Подсказка: Введите &6/drop2inventory&7 или &6/drop2inv&7 чтобы включить автоматический сбор дропа."
#message-when-breaking-block2: "&7Подсказка: Введите &6/drop2inventory&7 или &6/drop2inv&7 чтобы отключить автоматический сбор дропа."
#message-inventory-full: "&cYour inventory is full."

##### Spanish
#message-disabled: "&7La coleccion automatica de dropeos ha sido &cdeshabilitada&7."
#message-enabled: "&7La coleccion automatica de dropeos ha sido &ahabilitada&7."
#message-when-breaking-block: "&7Drop2Inventory: Utiliza &6/drop2inventory&7 o &6/drop2inv&7 para habilitar la coleccion automatica de dropeos."
#message-when-breaking-block2: "&7Drop2Inventory: Utiliza &6/drop2inventory&7 o &6/drop2inv&7 para deshabilitar la coleccion automatica de dropeos."
#message-inventory-full: "&cYour inventory is full."

##### Turkish
#message-disabled: "&7Otomatik toplama &cdeaktifleştirildi&7."
#message-enabled: "&7Otomatik toplama &aktifleştirildi&7."
#message-when-breaking-block: "&7İpucu: Otomatik toplamayı aktifleştirmek için &6/drop2inventory&7 ya da &6/drop2inv&7 yazınız."
#message-when-breaking-block2: "&7İpucu: Otomatik toplamayı deaktifleştirmek için &6/drop2inventory&7 ya da &6/drop2inv&7 yazınız."
#message-inventory-full: "&cEnvanterin dolu."

#########################
#####     Done!     #####
#########################

# you do not want this
debug: false

# please do not change the following line manually!
config-version: 121